exports.meme = require('./meme')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.getLocationData = require('./location')
exports.menuId = require('./menu')
exports.rugaapi = require('./rugaapi')
exports.point = require('./point')
exports.Insta = require('./Insta')